postprocessor:
  name: stoodx
  postprocessor_args:
    K: -1
    distance: cosine
    quantil: [0.0, 0.125, 0.25, 0.375, 0.5, 0.625, 0.75, 0.875]
    feature_name: avgpool
    # feature_name: encoder # for ViT
    partition: train



